itequipments/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    # Home and Auth
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), 
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),

    # Application
    path('all_equipment/', views.all_equipment, name='all_equipment'),
    path('all_equipment_search/', views.all_equipment_search, name='all_equipment_search'),
    path('not_used_equipment/', views.not_used_equipment, name='not_used_equipment'),
    path('add_equipment/', views.add_equipment, name='add_equipment'),
    path('view_equipment/<int:log_pk>', views.view_equipment, name='view_equipment'),
    path('view_not_equipment/<int:log_pk>', views.view_not_equipment, name='view_not_equipment'),
    path('edit_equipment/<int:log_pk>', views.edit_equipment, name='edit_equipment'),
    path('edit_not_equipment/<int:log_pk>', views.edit_not_equipment, name='edit_not_equipment'),
    path('edit_equipment/<int:log_pk>/delete', views.delete_equipment, name='delete_equipment'),
]

itlogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('itequipments/', include('itequipments.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

itequipments/models.py
from django.db import models
from django.contrib.auth.models import User 




# Create your models here.
class All_equipment(models.Model):

    assigned_to = models.CharField(max_length=100)
    asset_no = models.CharField(max_length=100)
    device_type = models.CharField(max_length=100)
    device_make = models.CharField(max_length=100)
    device_model = models.CharField(max_length=100)
    location_status = models.CharField(max_length=100)
    serial_no = models.CharField(max_length=100)    
    purchase_reason = models.TextField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True, blank=True)  
    price = models.DecimalField(max_digits= 10, decimal_places=2,blank=True)
    in_service= models.BooleanField(default=False)
    image = models.ImageField(upload_to ='eq_images/',blank=True)
    date_assigned = models.DateField(blank=True, null=True,auto_now_add=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        return self.asset_no

itequipments/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import All_equipment
from django.forms.widgets import NumberInput

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control"}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={"class":"form-control"}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={"class":"form-control"}))
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2')

    
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']



class EquipmentForm(forms.ModelForm):
        class Meta:
         model= All_equipment
         fields = [
            'asset_no',
            'device_type',
            'device_make',
            'device_model', 
            'location_status', 
            'serial_no', 
            'purchase_reason',
            'price',
            'in_service',
            'image',
            'date_assigned',
            'assigned_to'

         ]




        assigned_to = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        device_type = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        device_make = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        device_model = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        location_status = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        serial_no = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
        purchase_reason = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}))
        date_assigned = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    
    

itequipments/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from .models import All_equipment
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LoginForm, UserRegistrationForm, EquipmentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# Create your views here.
#Home
@login_required
def home(request):
    return render(request, 'home.html', {'section': 'home'})



#Registration
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
        return render(request, 'itequipments/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            
            # Save the User object
            new_user.save()
            return render(request,'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,'registration/register.html', {'user_form': user_form, 'error': 'Incorect data'})



############################################-APPLICATION-###########################################
@login_required
def all_equipment(request):
    equipment = All_equipment.objects.filter(in_service=True)

    eq_count = equipment.count()
    pag = Paginator(equipment, 10)
    page = request.GET.get('page')
    page_obj = pag.get_page(page)

    return render(request,'itequipments/all_equipment.html', {'equipment':equipment,'eqlist':page_obj, 'count': eq_count})


def all_equipment_search(request):
    if request.method == "POST":
        search_equipment = request.POST['search_equipment']
        searchList = All_equipment.objects.filter(asset_no__contains = search_equipment)
        return render(request,'itequipments/all_equipment_search.html', {'search_equipment':search_equipment, 'searchList':searchList})

@login_required
def not_used_equipment(request):
    equipment = All_equipment.objects.filter(in_service=False)
    return render(request,'itequipments/not_used_equipment.html', {'equipment':equipment})

@login_required
def add_equipment(request):
    if request.method == 'GET':
        equipment_no = All_equipment.objects.all().count()+1
        return render(request,'itequipments/add_equipment.html', {'form': EquipmentForm, 'count': equipment_no})
    else:
        try:
            form = EquipmentForm(request.POST,request.FILES)
            new_equipment= form.save(commit=False)
            new_equipment.user = request.user
            new_equipment.save()
            return redirect('all_equipment')
    
        except ValueError:
                return render(request, 'itequipments/add_equipment.html', {'form': EquipmentForm(), 'error': 'Bad data, Please try again'})

@login_required
def view_equipment(request,log_pk):
    equipment_detail= get_object_or_404(All_equipment, pk=log_pk)
    return render(request,'itequipments/view_equipment.html', {'equipment':equipment_detail})

@login_required
def view_not_equipment(request,log_pk):
    equipment_detail= get_object_or_404(All_equipment, pk=log_pk)
    return render(request,'itequipments/view_not_equipment.html', {'equipment':equipment_detail})


@login_required
def edit_equipment(request, log_pk):
    equipment_edit= get_object_or_404(All_equipment, pk=log_pk)

    if request.method =='GET':
        form = EquipmentForm(instance=equipment_edit)
        return render(request,'itequipments/edit_equipment.html', {'equipment':equipment_edit, 'form':form})

    else:
        if request.method =='POST':
            try:
                form = EquipmentForm(request.POST, request.FILES, instance=equipment_edit)
                form.save()
                return redirect('all_equipment')
            
            except ValueError:
                return render(request,'itequipments/edit_equipment.html', 
                {'equipment':equipment_edit, 'form':form, 'error': 'Incorrect data, Please try again.'})


@login_required
def edit_not_equipment(request, log_pk):
    equipment_edit= get_object_or_404(All_equipment, pk=log_pk)

    if request.method =='GET':
        form = EquipmentForm(instance=equipment_edit)
        return render(request,'itequipments/edit_not_equipment.html', {'equipment':equipment_edit, 'form':form})

    else:
        if request.method =='POST':
            try:
                form = EquipmentForm(request.POST, request.FILES, instance=equipment_edit)
                form.save()
                return redirect('not_used_equipment')
            
            except ValueError:
                return render(request,'itequipments/edit_not_equipment.html', 
                {'equipment':equipment_edit, 'form':form, 'error': 'Incorrect data, Please try again.'})


@login_required
def delete_equipment(request, log_pk ):
    equipment_delete = get_object_or_404(All_equipment, pk=log_pk)
    if request.method == 'POST':
        equipment_delete.delete()
        return redirect('all_equipment')
    return render(request,'itequipments/delete_equipment.html', {'equipment':equipment_delete})

itequipments/templates/itequipments/add_equipment.html
{% extends 'base.html' %}

{% block content %}


<div style="container">
{% if form.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <p>{{ error }}</p>
      <a href="{% url 'add_equipment' %}"><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></a>
  </div>
{% endif %}
</div>

<div class="container">
    

    <div class="col-md-8 center_div">

    <h1 class="header_fix">Add IT Equipment</h1>

    <form method="POST" action='{{ action_url }}' enctype='multipart/form-data' >
        {% csrf_token %}
        
        <p>
            <label for="id_asset_no">Asset no:</label>
            <input type="text" 
            style="color:rgb(37, 1, 1); 
            font-weight: 800;" 
            name="asset_no" maxlength="100" required id="id_asset_no" value="  IT0{{count}}" readonly></p>
        
          
          <p>
            <label for="id_device_type">Device type:</label>
            <input type="text" name="device_type" class="form-control" required id="id_device_type"></p>
        
          
          <p>
            <label for="id_device_make">Device make:</label>
            <input type="text" name="device_make" class="form-control" required id="id_device_make"></p>
        
          
          <p>
            <label for="id_device_model">Device model:</label>
            <input type="text" name="device_model" class="form-control" required id="id_device_model"></p>
        
          
          <p>
            <label for="id_location_status">Location status:</label>
              <select class="form-select" type="text" name="location_status" required id="id_location_status" aria-label="Default select example">
                <option selected>Select status</option>
                <option value="Stationary">Stationary</option>
                <option value="Mobile">Mobile</option>
              </select>
          </p>
        
          
          <p>
            <label for="id_serial_no">Serial no:</label>
            <input type="text" name="serial_no" class="form-control" required id="id_serial_no"></p>
        
          
          <p>
            <label for="id_purchase_reason">Purchase reason:</label>
            <textarea name="purchase_reason" cols="40" rows="10" class="form-control" required id="id_purchase_reason"></textarea></p>
        
          
          <p>
            <label for="id_price">Price:</label>
            <input type="number" name="price" step="0.01" id="id_price"></p>
        
          
          <p>
            <label for="id_in_service">In service:</label>
            <input type="checkbox" name="in_service" id="id_in_service"></p>
        
          
          <p>
            <label for="id_image">Image:</label>
            <input type="file" name="image" accept="image/*" id="id_image"></p>
        
          
          <p>
            <label for="id_date_assigned">Date assigned:</label>
            <input type="date" name="date_assigned" required id="id_date_assigned"></p>
        
          
          <p>
            <label for="id_assigned_to">Assigned to:</label>
            <input type="text" name="assigned_to" class="form-control" required id="id_assigned_to"></p>
               
        <br>

        <button type="submit" class="btn btn-primary">Submit</button>
        
        </form>
    </div>
</div>



{% endblock %}

itequipments/templates/itequipments/all_equipment.html
{% extends 'base.html' %}

{% block content %}


<div class="container all_eq">

  <h1 style="margin-top:30px"> All Equipment List</h1>

    <div class="col-md-4">
      <form action="{% url 'all_equipment_search' %}" method=POST>
        {% csrf_token %}
       <div class="mb-3">
       <label for="search_equipment" class="form-label"> </label>
       <input type="text" class="form-control" name="search_equipment" placeholder="Search Asset no."/>
      </div>
       <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>

    <br>
    <p>Total Equipement no.: {{count}}</p>
    <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">id#</th>
            <th scope="col">Asset #</th>
            <th scope="col">Assigned To:</th>
            <th scope="col">Device Type:</th>
            <th scope="col">Device Model:</th>
            <th scope="col">Date Created:</th>
            <th scope="col">Date Assigned:</th>
            <th scope="col">In Service:</th>
            <th scope="col">Location Status:</th>
          </tr>
        </thead>
       
        
        <tbody>
            {% for item in eqlist %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url "view_equipment" item.id %}"> {{item.asset_no}} </a></td>
            <td>{{item.assigned_to}}</td>
            <td>{{item.device_type}}</td>
            <td>{{item.device_model}}</td>
            <td>{{item.created_date}}</td>
            <td>{{item.date_assigned}}</td>
            <td>{{item.in_service}}</td>
            <td>{{item.location_status}}</td>
          </tr>
          {% endfor %}
        </table>
        

        <br>

        {% if eqlist.has_previous %}
        <a href="?page=1">&laquo First</a>
        <a href="?page={{eqlist.previous_page_number}}">Previous</a>
        {% endif %}

        Page {{ eqlist.number }} of {{ eqlist.paginator.num_pages }}

        {% if eqlist.has_next %}
        <a href="?page={{eqlist.next_page_number}}">next</a>
        <a href="?page={{eqlist.previous.num_pages}}">Last &raquo</a>
        {% endif %}

    </div>

       

{% endblock %}

itequipments/templates/itequipments/all_equipment_search.html
{% extends 'base.html' %}

{% block content %}


<div class="container all_eq">


  <h1 class="header_fix"> Searched Equipment by Asset no: <span style="color: blue;"> {{search_equipment}} </span> </h1>


  <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">id#</th>
          <th scope="col">Asset #</th>
          <th scope="col">Assigned To:</th>
          <th scope="col">Device Type:</th>
          <th scope="col">Device Model:</th>
          <th scope="col">Date Created:</th>
          <th scope="col">Date Assigned:</th>
          <th scope="col">In Service:</th>
          <th scope="col">Location Status:</th>
        </tr>
      </thead>
     
      
      <tbody>
          {% for search in searchList %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td><a href="{% url "view_equipment" search.id %}"> {{search.asset_no}} </a></td>
          <td>{{search.assigned_to}}</td>
          <td>{{search.device_type}}</td>
          <td>{{search.device_model}}</td>
          <td>{{search.created_date}}</td>
          <td>{{search.date_assigned}}</td>
          <td>{{search.in_service}}</td>
          <td>{{search.location_status}}</td>
        </tr>
        {% endfor %}
      </table>
      

    <!--end of Pagination-->
    {% endblock %}

itequipments/templates/itequipments/delete_equipment.html
{% extends 'base.html' %}


{% block content %}

<div class="container" style="margin-top: 100px;">
    
    <div class="col-md-8 center_div">

 
<form action="" method="POST"> 
    {% csrf_token %}
    <h1>Are you sure you want to delete this IT Equipment: {{equipment.asset_no}}?</h1>
    <input class="btn btn-danger" type="submit" value="Yes" /> 
    <a href="{% url 'view_equipment' equipment.id  %}"><div class="btn btn-primary">Cancel</div></a>
    

</div>
</div>

{% endblock %}

itequipments/templates/itequipments/edit_equipment.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit IT Equipment</h1>

{{ error }}

<form method="POST" enctype='multipart/form-data'>
{% csrf_token %}

{{ form.as_p }}

<button type="submit">Submit</button>
<a href="{% url 'view_equipment' equipment.id  %}"><div class="btn btn-primary">Cancel</div></a>

</form>


{% endblock %}

itequipments/templates/itequipments/edit_not_equipment.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <p>{{ error }}</p>
      <a href="{% url 'add_equipment' %}"><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></a>
  </div>
{% endif %}

<div class="container">
    

    <div class="col-md-8 center_div">

    <h1 class="header_fix">Edit IT Equipment</h1>

<form method="POST" action='{{ action_url }}' enctype='multipart/form-data' >
        {% csrf_token %}
        

<p>
    <label for="id_asset_no">Asset no:</label>
    <input type="text" name="asset_no" maxlength="100" required id="id_asset_no" value="{{equipment.asset_no}}" readonly></p>

  
  <p>
    <label for="id_device_type">Device type:</label>
    <input type="text" name="device_type" class="form-control" required id="id_device_type" value="{{equipment.device_type}}"></p>

  
  <p>
    <label for="id_device_make">Device make:</label>
    <input type="text" name="device_make" class="form-control" required id="id_device_make" value="{{equipment.device_make}}"></p>

  
  <p>
    <label for="id_device_model">Device model:</label>
    <input type="text" name="device_model" class="form-control" required id="id_device_model" value="{{equipment.device_model}}"></p>

  
  <p>
    <label for="id_location_status">Location status:</label>
    <input type="text" name="location_status" class="form-control" required id="id_location_status" value="{{equipment.location_status}}"></p>

  
  <p>
    <label for="id_serial_no">Serial no:</label>
    <input type="text" name="serial_no" class="form-control" required id="id_serial_no" value="{{equipment.serial_no}}"></p>

  
  <p>
    <label for="id_purchase_reason">Purchase reason:</label>
    <textarea name="purchase_reason" cols="40" rows="10" class="form-control" required id="id_purchase_reason">{{equipment.purchase_reason}}</textarea></p>

  
  <p>
    <label for="id_price">Price:</label>
    <input type="number" name="price" step="0.01" id="id_price" value="{{equipment.price}}"></p>

  
  <p>
    <label for="id_in_service">In service:</label>
    <input type="checkbox" name="in_service" id="id_in_service"></p>

  
  <p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" accept="image/*" id="id_image"></p>

  
  <p>
    <label for="id_date_assigned">Date assigned:</label>
    <input name="date_assigned" required id="id_date_assigned" style="color:grey" value="{{equipment.date_assigned}}" readonly></p>

  
  <p>
    <label for="id_assigned_to">Assigned to:</label>
    <input type="text" name="assigned_to" class="form-control" required id="id_assigned_to" value="{{equipment.assigned_to}}"></p>


    
   <br>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'view_equipment' equipment.id  %}"><div class="btn btn-danger">Cancel</div></a>
    

</form>

</div>
</div>

{% endblock %}

itequipments/templates/itequipments/not_used_equipment.html
{% extends 'base.html' %}

{% block content %}


<div class="container all_eq">

  <h1 style="margin-top:30px"> Equipment <span style="font-size:30px">*Not in Use*</span> List</h1>
  <br>
    <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">id#</th>
            <th scope="col">Asset #</th>
            <th scope="col">Assigned To:</th>
            <th scope="col">Device Type:</th>
            <th scope="col">Device Model:</th>
            <th scope="col">Date Created:</th>
            <th scope="col">Date Assigned:</th>
            <th scope="col">In Service:</th>
            <th scope="col">Location Status:</th>
          </tr>
        </thead>
       
        
        <tbody>
            {% for item in equipment %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url "view_not_equipment" item.id %}"> {{item.asset_no}} </a></td>
            <td>{{item.assigned_to}}</td>
            <td>{{item.device_type}}</td>
            <td>{{item.device_model}}</td>
            <td>{{item.created_date}}</td>
            <td>{{item.date_assigned}}</td>
            <td>{{item.in_service}}</td>
            <td>{{item.location_status}}</td>
          </tr>
          {% endfor %}
        </table>
        
    </div>

    {% endblock %}

itequipments/templates/itequipments/view_equipment.html
{% extends 'base.html' %}

{% block content %}


        <div class="container" style="width:1000px; margin-top:70px;">
            <div class="title h1 text-center"><h1> IT Equipment: {{equipment.asset_no}} </h1></div>
            <div class="card ">
              <div class="row ">
          
                <div class="col-sm-7">
                  <div class="container card-block" style="margin: 40px;">
                    <!--           <h4 class="card-title">Small card</h4> -->
                    <p>Assigned_to: <span style="font-weight: 700">{{equipment.assigned_to}}</span></p>
                    <p><i class="fas fa-file"></i>Asset no: <span style="font-weight: 700">{{equipment.asset_no}}</p></span>
                    <p>Equipment Price: <span style="font-weight: 700">£{{equipment.price}}</p></span>
                    <p>Device Type: <span style="font-weight: 700">{{equipment.device_type}}</p></span>
                    <p>Device Make: <span style="font-weight: 700">{{equipment.device_make}}</p></span>
                    <p>Device model: <span style="font-weight: 700">{{equipment.device_model}}</p></span>
                    <p>Serial no: <span style="font-weight: 700">{{equipment.serial_no}}</p></span>
                    <p>Location status: <span style="font-weight: 700">{{equipment.location_status}}</p></span>
                    <p>In service: <span style="font-weight: 700">{{equipment.in_service}}</p></span>
                    <p>Purchase reason: <span style="font-weight: 700">{{equipment.purchase_reason}}</p></span>
                    
                  </div>
                  
                </div>
          
                {% if equipment.image %}
                <div class="col-sm-5">
                  <img class="d-block w-100 rounded" style="padding: 0px;" src="{{ equipment.image.url }}" alt="">
                </div>
              </div>
            </div>

            {% else %}

            <div class="col-sm-5">
                <img class="d-block w-100 rounded" style="padding: 0px;" src="" alt="">
              </div>
            </div>
          </div>
            {% endif %}

    
            
            <div class="container d-flex" style="margin-top: 15px;">
                
            
                <form action="{% url 'edit_equipment' equipment.id %}" method="GET"> 
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" style="margin-right: 10px;">Edit</button>
               </form> 
            
                        
        
            <button type="button" class="btn btn-danger">
                    <a href="{% url 'delete_equipment' equipment.id %}" style="color: white;">Delete</a>
            </button>
            
            </div>
        

        </div>



{% endblock %}

itequipments/templates/itequipments/view_not_equipment.html
{% extends 'base.html' %}

{% block content %}


        <div class="container" style="width:1000px; margin-top:70px;">
            <div class="title h1 text-center"><h1> IT Equipment: {{equipment.asset_no}} </h1></div>
            <div class="card ">
              <div class="row ">
          
                <div class="col-sm-7">
                  <div class="container card-block" style="margin: 40px;">
                    <!--           <h4 class="card-title">Small card</h4> -->
                    <p>Assigned_to: {{equipment.assigned_to}}</p>
                    <p>Asset no: {{equipment.asset_no}}</p>
                    <p>Equipment Price: £{{equipment.price}}</p>
                    <p>Device Type: {{equipment.device_type}}</p>
                    <p>Device Make: {{equipment.device_make}}</p>
                    <p>Device model: {{equipment.device_model}}</p>
                    <p>Serial no: {{equipment.serial_no}}</p>
                    <p>Location status: {{equipment.location_status}}</p>
                    <p>In service: {{equipment.in_service}}</p>
                    <p>Purchase reason: {{equipment.purchase_reason}}</p>
                    
                  </div>
                  
                </div>
          
                {% if equipment.image %}
                <div class="col-sm-5">
                  <img class="d-block w-100 rounded" style="padding: 0px;" src="{{ equipment.image.url }}" alt="">
                </div>
              </div>
            </div>

            {% else %}

            <div class="col-sm-5">
                <img class="d-block w-100 rounded" style="padding: 0px;" src="" alt="">
              </div>
            </div>
          </div>
            {% endif %}

    
            
            <div class="container d-flex" style="margin-top: 15px;">
                
            
                <form action="{% url 'edit_not_equipment' equipment.id %}" method="GET"> 
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" style="margin-right: 10px;">Edit</button>
               </form> 
            
                        
        
            <button type="button" class="btn btn-danger">
                    <a href="{% url 'delete_equipment' equipment.id %}" style="color: white;">Delete</a>
            </button>
            
            </div>
        

        </div>



{% endblock %}